version: '3.8'

services:
  app:
    image: node:14
    container_name: dokko-server
    build:
      context: .
      dockerfile: Dockerfile
    user: 'node'
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
      - VERSION=1.0
    volumes:
      - .:/usr/src/app
      - ../usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - webnet
    depends_on:
      - redis
      - postgres
    tty: true
    command: npm run start:dev

  redis:
    container_name: redis
    image: redis:5
    networks:
      - webnet

  postgres:
    container_name: postgres
    image: postgres:12
    networks:
      - webnet
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
      - ${POSTGRES_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d

networks:
  webnet:
volumes:
  pgdata:
